/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-01-02 07:20:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("  <head> \n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <title></title>\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\n");
      out.write("    <!-- Bootstrap CSS-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <!-- Font Awesome CSS-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\n");
      out.write("    <!-- Custom Font Icons CSS-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font.css\">\n");
      out.write("    <!-- Google fonts - Muli-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Muli:300,400,700\">\n");
      out.write("    <!-- theme stylesheet-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.default.css\" id=\"theme-stylesheet\">\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\n");
      out.write("    <!-- Favicon-->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/WSO2_Software_Logo.png\">\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <header class=\"header\">   \n");
      out.write("      <nav class=\"navbar navbar-expand-lg\">\n");
      out.write("        <div class=\"search-panel\">\n");
      out.write("          <div class=\"search-inner d-flex align-items-center justify-content-center\">\n");
      out.write("            <div class=\"close-btn\">Close <i class=\"fa fa-close\"></i></div>\n");
      out.write("            <form id=\"searchForm\" action=\"#\">\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <input type=\"search\" name=\"search\" placeholder=\"What are you searching for...\">\n");
      out.write("                <button type=\"submit\" class=\"submit\">Search</button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\t\t\n");
      out.write("        <div class=\"container-fluid d-flex align-items-center justify-content-between\">\n");
      out.write("          <div class=\"navbar-header\"><a href=\"index.html\" class=\"navbar-brand\">\n");
      out.write("              <div class=\"brand-text brand-big visible text-uppercase\"><strong class=\"text-primary\">DASH</strong><strong>BOARD</strong></div>\n");
      out.write("              <div class=\"brand-text brand-sm\"><strong class=\"text-primary\">D</strong><strong>B</strong></div></a>\n");
      out.write("            <button class=\"sidebar-toggle\"><i class=\"fa fa-long-arrow-left\"></i></button>\n");
      out.write("          </div>\n");
      out.write("\t\t  \n");
      out.write("          <ul class=\"right-menu list-inline no-margin-bottom\">    \n");
      out.write("            <li class=\"list-inline-item\"><a href=\"#\" class=\"search-open nav-link\"><i class=\"icon-magnifying-glass-browser\"></i></a></li>\n");
      out.write("            \n");
      out.write("            <li class=\"list-inline-item logout\">                   <a id=\"logout\" href=\"login.html\" class=\"nav-link\">Logout <i class=\"icon-logout\"></i></a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("    </header>\n");
      out.write("\t\n");
      out.write("    <div class=\"d-flex align-items-stretch\">\n");
      out.write("      <!-- Sidebar Navigation-->\n");
      out.write("      <nav id=\"sidebar\">\n");
      out.write("        <div class=\"sidebar-header d-flex align-items-center\">\n");
      out.write("          <div><img src=\"img/WSO2_Software_Logo.png\" alt=\"...\" class=\"img-fluid\"></div>\n");
      out.write("\t\t  \n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("\t\t\n");
      out.write("\t\t<span class=\"heading\">Main</span>\n");
      out.write("        <ul class=\"list-unstyled\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a><br></br>\n");
      out.write("   \n");
      out.write("   \t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/engagementList\">engagementList</a><br></br>\n");
      out.write("   \n");
      out.write("  \t\t\t\t <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Thisweekproject\">This week project</a><br></br>\n");
      out.write("   \n");
      out.write("  \t\t\t\t <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Lastweekproject\">Last week project</a><br></br>\n");
      out.write("    \n");
      out.write("                \n");
      out.write("      </nav>\n");
      out.write("      <div class=\"page-content\">\n");
      out.write("\t\t\n");
      out.write("\t  \n");
      out.write("        <div class=\"page-header\">\n");
      out.write("          <div class=\"container-fluid\">\n");
      out.write("\t\t  <h2 class=\"h5 no-margin-bottom\">\n");
      out.write("\t\t\t\n");
      out.write("            Ongoing Project Details</h2>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <section class=\"no-padding-bottom\">\n");
      out.write("          <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-lg-6\">\n");
      out.write("               ************88\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <footer class=\"footer\">\n");
      out.write("          <div class=\"footer__block block no-margin-bottom\">\n");
      out.write("            <div class=\"container-fluid text-center\">\n");
      out.write("              <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->\n");
      out.write("              <p class=\"no-margin-bottom\">2017 &copy; Your company. Design by </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Javascript files-->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\"> </script>\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\n");
      out.write("    <script src=\"vendor/chart.js/Chart.min.js\"></script>\n");
      out.write("    <script src=\"js/charts-home.js\"></script>\n");
      out.write("    <script src=\"js/front.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
